openapi: '3.0.2'
info:
  description: HR User Retrieval API for the Bamboo HR system API
  title: HR User Retrieval API
  version: '1.0'
servers:
  - url: https://localhost:3000/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
